# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HKxFnvxijMbclUUwoNp_u8RWHGR_Jn45
"""


import streamlit as st
import joblib
import numpy as np

# 1. Load the model you downloaded in Step 1
# (Make sure this python file and 'aqi_model.pkl' are in the same folder)
model = joblib.load("aqi_model (4).pkl")

# Set up the Streamlit page title
st.title("Air Quality Index (AQI) Predictor 🌦️")
st.write("Enter the pollutant levels below to predict the overall AQI.")

# 2. Recreate the 6 features your Random Forest model expects
pm25 = st.number_input("PM2.5 Level", min_value=0.0, value=30.0)
pm10 = st.number_input("PM10 Level", min_value=0.0, value=60.0)
no2  = st.number_input("NO2 Level", min_value=0.0, value=15.0)
so2  = st.number_input("SO2 Level", min_value=0.0, value=10.0)
co   = st.number_input("CO Level", min_value=0.0, value=1.0)
o3   = st.number_input("O3 (Ozone) Level", min_value=0.0, value=20.0)

# Create a button for prediction
if st.button("Predict AQI"):

    # 3. Format the data into a 2D array matching the original order:
    # ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3']
    data = [[pm25, pm10, no2, so2, co, o3]]

    # 4. Make the prediction
    predicted_aqi = model.predict(data)[0]

    # 5. Display results beautifully based on AQI values
    st.subheader(f"Predicted AQI: {round(predicted_aqi, 2)}")

    if predicted_aqi <= 50:
        st.success("Good 🟢")
    elif predicted_aqi <= 100:
        st.info("Satisfactory 🟡")
    elif predicted_aqi <= 200:
        st.warning("Moderate 🟠")
    elif predicted_aqi <= 300:
        st.error("Poor 🔴")
    else:
        st.error("Severe 💀")
